# Generated by Django 3.2.5 on 2021-07-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210716_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['nome'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AddField(
            model_name='course',
            name='about',
            field=models.TextField(blank=True, verbose_name='Sobre o Curso'),
        ),
        migrations.AlterField(
            model_name='course',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição Simples'),
        ),
    ]
